name = "leetcode-job-worker"
type = "javascript"

[triggers]
crons = ["*/1 * * * *"]

[env.production]
vars = {
  UPSTASH_REDIS_REST_URL = "https://your-upstash-url",
  UPSTASH_REDIS_REST_TOKEN = "your-upstash-token"
}
